apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: {{ .Values.fromReplicaCount }}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: nombre_de_la_imagen_docker
          ports:
            - containerPort: 8888